### ISSUE TITLE
Nice but what is the pricing model?

### ISSUE THREAD

**Issue by idibidiart** [packetzoom/react-native#1]
hi,

I'm sold based on your literature but what is the pricing? seems like you have some edge servers that make the last mile optimization possible... and the idea is that I would pay to use your edge servers? 

It isn't clear from reading your website.

**Comment by bexp** [comment]
There is free tier available if you're just getting started (you don't have to enter or credit card to start using service) otherwise there is contact form on website or support@packetzoom.com for pricing info.
